### ISSUE TITLE
Don't forget to include reference to creating the dandi_cache_table during DB initialization

### ISSUE THREAD

**Issue by aaronkanzer** [lincbrain/handbook#7]
`heroku run python manage.py createcachetable dandi_cache_table --app linc-staging-terraform` was necessary in order to get the dandi_cache_table to be created -- this table renders dandi-related stats in the UI

**Comment by kabilar** [comment]
Hi @aaronkanzer, should this be added to https://github.com/dandi/handbook/pull/104?

**Comment by aaronkanzer** [comment]
> Hi @aaronkanzer, should this be added to [dandi#104](https://github.com/dandi/handbook/pull/104)?

Thanks @kabilar -- I've added docs here: https://github.com/dandi/handbook/pull/104/commits/7dea59bda844d83a437d8aff7b338381a7429b77#r1811369220, and will close out this issue
